FROM python:3.12-slim

WORKDIR /app

# Copy all files from backend folder
COPY . /app/

RUN pip install --no-cache-dir -r requirements.txt

CMD sh -c "uvicorn main:app --host 0.0.0.0 --port ${PORT:-8000}"
